### ISSUE TITLE
Game music not in relative path

### ISSUE THREAD

**Issue by ssalmela** [raivohdus/autotetris#1]
(base) C:\code\autotetris\autotetris>python game.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\code\autotetris\autotetris\game.py", line 152, in <module>
    pygame.mixer.music.load('D:\\code\\AI\\tetris2\\music\\techno-tetris-theme.mp3')
pygame.error: No such file or directory: 'D:\code\AI\tetris2\music\techno-tetris-theme.mp3'.

**Comment by raivohdus** [comment]
Done with https://github.com/raivohdus/autotetris/tree/2d0b0e54a894acc3a376150647dafb1aaa27721e

**Comment by raivohdus** [comment]
closed
